driver:
  name: vagrant
  # provided as an example, see https://github.com/test-kitchen/kitchen-vagrant for more info
  #
  # customize:
  #   memory: 1024
  network:
     - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: trusty-server-cloudimg-amd64-vagrant-disk1
      box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

suites:
  - name: default
    run_list:
      - recipe[_logstash_server3_rm::default]
    attributes:
