driver:
  name: vagrant
  # provided as an example, see https://github.com/test-kitchen/kitchen-vagrant for more info
  #
  # customize:
  #   memory: 1024
  # network:
  #   - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-13.10
    driver_config:
      box: saucy-server-cloudimg-amd64-vagrant-disk1
      box_url: http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box
    run_list:
      - recipe[apt]
  - name: centos-6.5
    driver_config:
      box: centos65-x86_64-20131205
      box_url: https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box

suites:
  - name: default
    run_list:
      - recipe[verifi_skeleton::default]
    attributes:
  - name: server
    run_list:
      - recipe[verifi_skeleton::default]
    attributes:
